const images = {
  ash_berlin_hellersdorf: require('@/assets/mensas/ash_berlin_hellersdorf.jpg'),
  hfm_charlottenstrae: require('@/assets/mensas/hfm_charlottenstrae.jpg'),
  bht_luxemburger_strae: require('@/assets/mensas/bht_luxemburger_strae.jpg'),
  backshop_bht_luxemburger_straee: require('@/assets/mensas/bht_luxemburger_strae.jpg'),
  spti_bht_haus_grashofe: require('@/assets/mensas/spti_bht_haus_grashof.jpg'),
  htw_treskowallee: require('@/assets/mensas/htw_treskowallee.jpg'),
  htw_wilhelminenhof: require('@/assets/mensas/htw_wilhelminenhof.jpg'),
  charit_zahnklinik: require('@/assets/mensas/charit_zahnklinik.jpg'),
  hu_sd: require('@/assets/mensas/hu_sd.jpg'),
  spti_charit_zahnklinik: require('@/assets/mensas/spti_charit_zahnklinik.jpg'),
  backshop_hfm_charlottenstrae: require('@/assets/mensas/backshop_hfm_charlottenstrae.jpg'),
  ehb_teltower_damm: require('@/assets/mensas/ehb_teltower_damm.jpg'),
  fu_herrenhaus_dppel: require('@/assets/mensas/fu_herrenhaus_dppel.jpg'),
  fu_i_shokud: require('@/assets/mensas/fu_i_shokud.jpg'),
  fu_ii: require('@/assets/mensas/fu_ii.jpg'),
  fu_koserstrae: require('@/assets/mensas/fu_koserstrae.jpg'),
  fu_lankwitz_malteserstrae: require('@/assets/mensas/fu_lankwitz_malteserstrae.jpg'),
  fu_pharmazie: require('@/assets/mensas/fu_pharmazie.jpg'),
  backshop_fu_rechtswissenschaften: require('@/assets/mensas/backshop_fu_rechtswissenschaften.jpg'),
  spti_shokud_fu_i: require('@/assets/mensas/spti_shokud_fu_i.jpg'),
  hfs_ernst_busch: require('@/assets/mensas/hfs_ernst_busch.jpg'),
  backshop_htw_wilhelminenhof: require('@/assets/mensas/backshop_htw_wilhelminenhof.jpg'),
  hwr_badensche_strae: require('@/assets/mensas/hwr_badensche_strae.jpg'),
  backshop_hwr_altfriedrichsfelde: require('@/assets/mensas/backshop_hwr_altfriedrichsfelde.jpg'),
  hu_nord: require('@/assets/mensas/hu_nord.jpg'),
  hu_oase_adlershof: require('@/assets/mensas/hu_oase_adlershof.jpg'),
  backshop_hu_ct: require('@/assets/mensas/backshop_hu_ct.jpg'),
  backshop_hu_oase_adlershof: require('@/assets/mensas/hu_oase_adlershof.jpg'),
  khsb: require('@/assets/mensas/khsb.jpg'),
  tu_hardenbergstrae: require('@/assets/mensas/tu_hardenbergstrae.jpg'),
  tu_marchstrae: require('@/assets/mensas/tu_marchstrae.jpg'),
  tu_veggie_20__die_vegane_mensa: require('@/assets/mensas/tu_veggie_20__die_vegane_mensa.jpg'),
  backshop_tu_hardenbergstrae: require('@/assets/mensas/tu_hardenbergstrae.jpg'),
  backshop_tu_wetterleuchten: require('@/assets/mensas/backshop_tu_wetterleuchten.jpg'),
  khs_weiensee: require('@/assets/mensas/khs_weiensee.jpg'),
  spti_tu_hardenbergstrae: require('@/assets/mensas/tu_hardenbergstrae.jpg'),
};

export default images;
